apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas01-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: nas.lab.lemisieur.com
  share: /var/nfs/shared/lab_k8s_storage
reclaimPolicy: Retain
volumeBindingMode: Immediate