apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-storage
  namespace: storage
spec:
  storageClassName: nas01-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi