services:
  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.3
    container_name: jellyseerr-01
    ports:
      - 5055:5055
    environment:
      - TZ=America/Toronto
    volumes:
      - /share/containers/jellyseerr/config:/app/config
    dns:
      - 192.168.4.1
    restart: unless-stopped
  readarr:
    container_name: readarr-01
    image: linuxserver/readarr:develop
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 8787:8787
    volumes:
      - /share/containers/readarr/config:/config
      - /share/downloads:/mount/downloads
  qbittorrent:
    container_name: qbittorrent-01
    image: linuxserver/qbittorrent:5.1.2
    restart: unless-stopped
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      - 2099:2099 #vpm
    volumes:
      - /share/containers/qbittorrent/config:/config
      - /share/containers/qbittorrent/themes:/themes
      - /share/downloads:/mount/downloads
    environment:
      - PUID=1000
      - PGID=1000
