apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: traefik
spec:
  type: ExternalName
  externalName: hb.ip.lab.lemisieur.com
  ports:
  - port: 8581
    targetPort: 8581
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homebridge
  namespace: traefik
spec:
  entryPoints:
  - websecure
  tls:
    secretName: lab-lemisieur-com
  routes:
  - kind: Rule
    match: Host(`hb.lab.lemisieur.com`)
    services:
    - name: homebridge
      port: 8581
      scheme: http
      passHostHeader: true
      weight: 100