apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: traefik
spec:
  type: ExternalName
  externalName: ha.ip.lab.lemisieur.com
  ports:
  - port: 8123
    targetPort: 8123
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  namespace: traefik
spec:
  entryPoints:
  - websecure
  tls:
    secretName: lab-lemisieur-com
  routes:
  - kind: Rule
    match: Host(`ha.lab.lemisieur.com`)
    services:
    - name: homeassistant
      port: 8123
      scheme: http
      weight: 100