apiVersion: v1
kind: Service
metadata:
  name: pve-01
  namespace: traefik
spec:
  type: ExternalName
  externalName: pve-01.ip.lab.lemisieur.com
  ports:
  - port: 8006
    targetPort: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: pve-02
  namespace: traefik
spec:
  type: ExternalName
  externalName: pve-02.ip.lab.lemisieur.com
  ports:
  - port: 8006
    targetPort: 8006
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: pve-transport
  namespace: traefik
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pve
  namespace: traefik
spec:
  entryPoints:
  - websecure
  tls:
    secretName: lab-lemisieur-com
  routes:
  - kind: Rule
    match: Host(`pve.k8s.lab.lemisieur.com`) || Host(`pve.lab.lemisieur.com`)
    services:
    - name: pve-01
      port: 8006
      scheme: https
      serversTransport: pve-transport
      weight: 100
    - name: pve-02
      port: 8006
      scheme: https
      serversTransport: pve-transport
      weight: 100