apiVersion: v1
kind: Service
metadata:
  name: pve
  namespace: traefik
spec:
  type: ExternalName
  externalName: pve-01.ip.lab.lemisieur.com
  ports:
  - port: 8006
    targetPort: 8006
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pve
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`pve.k8s.lab.lemisieur.com`)
    services:
    - name: pve
      port: 8006
      scheme: https
      serversTransport: pve-transport
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: pve-transport
  namespace: traefik
spec:
  insecureSkipVerify: true