
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  entryPoints:
  - websecure
  tls:
    secretName: k8s-lab-lemisieur-com
  routes:
  - kind: Rule
    match: Host(`traefik.k8s.lab.lemisieur.com`)
    middlewares:
    - name: oauth2-signin
      namespace: oauth2-proxy
    services:
    - kind: TraefikService
      name: api@internal