apiVersion: v1
kind: Service
metadata:
  name: vscode
  namespace: traefik
spec:
  type: ExternalName
  externalName: macmini-01.ip.lab.lemisieur.com
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: vscode-transport
  namespace: traefik
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vscode
  namespace: traefik
spec:
  entryPoints:
  - websecure
  tls:
    secretName: lab-lemisieur-com
  routes:
  - kind: Rule
    match: Host(`vscode.lab.lemisieur.com`)
    services:
    - name: vscode
      port: 8080
      scheme: https
      serversTransport: vscode-transport
      weight: 100