apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: lemisieur-k8s-secrets
spec:
  provider:
    azurekv:
      vaultUrl: "https://lemisieur-k8s-secrets.vault.azure.net"
      authSecretRef:
        clientId:
          name: azure-sp-creds
          key: client_id
        clientSecret:
          name: azure-sp-creds
          key: client_secret