apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: lemisieur-k8s-secrets
spec:
  provider:
    azurekv:
      vaultUrl: "https://lemisieur-k8s-secrets.vault.azure.net"
      authType: ServicePrincipal
      tenantId: 0bd8c7f7-2a0b-46b8-9b7d-934844b3dee7
      authSecretRef:
        clientId:
          name: azure-sp-creds
          key: client_id
        clientSecret:
          name: azure-sp-creds
          key: client_secret
