apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secret
  namespace: oauth2-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: emisieur-k8s-secrets
  target:
    name: oauth2-proxy-secret
    creationPolicy: Owner
    template:
      data:
        OAUTH2_PROXY_CLIENT_ID: "{{ .client_id }}"
        OAUTH2_PROXY_CLIENT_SECRET: "{{ .client_secret }}"
        OAUTH2_PROXY_COOKIE_SECRET: "{{ .cookie_secret }}"
        OAUTH2_PROXY_OIDC_ISSUER_URL: "https://login.microsoftonline.com/{{ .tenant_id }}/v2.0"
  data:
    - secretKey: client_id
      remoteRef:
        key: oauth2proxy-azsp-clientid
    - secretKey: client_secret
      remoteRef:
        key: oauth2proxy-azsp-clientsecret
    - secretKey: cookie_secret
      remoteRef:
        key: oauth2proxy-cookie-secret
    - secretKey: tenant_id
      remoteRef:
        key: oauth2proxy-azsp-tenantid