apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/lemisieur-services/homelab.git
      targetRevision: main
      path: k8s/argocd/config
    - repoURL: https://github.com/lemisieur-services/homelab.git
      targetRevision: main
      path: k8s/argocd/projects
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: true
  destination:
    server: https://kubernetes.default.svc