apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-stores
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lemisieur-services/homelab.git
    targetRevision: main
    path: k8s/eso
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true