apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso
  namespace: argocd  # Adjust to your ArgoCD namespace
spec:
  project: eso
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: "1.3.1"
      helm:
        releaseName: external-secrets
    - repoURL: https://github.com/lemisieur-services/homelab.git
      targetRevision: main
      path: k8s/eso
  destination:
    server: https://kubernetes.default.svc  # In-cluster; adjust for remote clusters
    namespace: external-secrets
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true