apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: longhorn
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.1
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
    - chart: oauth2-proxy
      repoURL: https://oauth2-proxy.github.io/manifests
      targetRevision: 10.1.3
      helm:
        values: |
          config:
            existingSecret: oauth2-proxy-secret
            configFile: |
             oidc_email_claim = "upn"
             email_domains = ["*"]
             cookie_secure = false
             provider = "entra-id"
             oidc_issuer_url = "https://login.microsoftonline.com/0bd8c7f7-2a0b-46b8-9b7d-934844b3dee7/v2.0"
             redirect_url = "https://longhorn.k8s.lab.lemisieur.com/oauth2/callback"
             scope = "openid email profile"
             pass_access_token = true
             pass_authorization_header = true
             pass_user_headers = true
             set_authorization_header = true
              
    - repoURL: https://github.com/lemisieur-services/homelab.git
      targetRevision: main
      path: k8s/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true