apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: longhorn
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.1
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
    - chart: oauth2-proxy
      repoURL: https://oauth2-proxy.github.io/manifests
      targetRevision: 10.1.2
      helm:
        values: |
          envFrom:
            - secretRef:
                name: oauth2-proxy-secret
            - configMapRef:
                name: oauth2-proxy-config
          config:
            clientID: ""
            clientSecret: ""
            cookieSecret: ""
    - repoURL: https://github.com/lemisieur-services/homelab.git
      targetRevision: main
      path: k8s/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true