apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  sources:
    - chart: metrics-server
      repoURL: 
      targetRevision: 3.13.0
      helm:
        values: |
          args:
            - --kubelet-insecure-tls
          tolerations:
            - key: node.kubernetes.io/role
              operator: Equal
              value: proxy
              effect: NoSchedule
          nodeSelector:
            node.kubernetes.io/class: proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: true
