apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: default
  source:
    - repoURL: https://github.com/lemisieur-services/homelab.git
      targetRevision: main
      path: k8s/oauth2-proxy
    - chart: oauth2-proxy
      repoURL: https://oauth2-proxy.github.io/manifests
      targetRevision: 10.1.3
      helm:
        values: |
          config:
            existingSecret: gh-oauth-secret
            configFile: |
              provider = "github"
              email_domains = ["*"]
              cookie_secure = true
              cookie_domains = ["k8s.lab.lemisieur.com"]
              whitelist_domains = ["k8s.lab.lemisieur.com"]
              reverse_proxy = true
              redirect_url = "https://oauth.k8s.lab.lemisieur.com/oauth2/callback"
              scope = "read:user user:email"
              pass_access_token = true
              pass_authorization_header = true
              pass_user_headers = true
              set_authorization_header = true
  destination:
    server: https://kubernetes.default.svc
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true