apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: oauth2-proxy
  sources:
    - chart: oauth2-proxy
      repoURL: https://oauth2-proxy.github.io/manifests
      targetRevision: 10.1.2
      helm:
        values: |
          envFrom:
            - secretRef:
                name: oauth2-proxy-secret
            - configMapRef:
                name: oauth2-proxy-config
    - repoURL: https://github.com/lemisieur-services/homelab.git
      targetRevision: main
      path: k8s/oauth2-proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true