apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  sources:
    - chart: portainer
      repoURL: https://portainer.github.io/k8s/
      targetRevision: 2.33.6
      helm:
        values: |
          enterpriseEdition:
            enabled: true
            image:
              tag: lts
          persistence:
            storageClass: local-ssd          
    # - repoURL: https://github.com/lemisieur-services/homelab.git
    #   targetRevision: main
    #   path: k8s/portainer
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true