apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-routes
  namespace: argocd
spec:
  project: gitops-01
  source:
    repoURL: https://github.com/lemisieur-services/homelab.git
    targetRevision: main
    path: k8s/traefik/routes
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true