apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oauth
  namespace: longhorn
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`oauth.k8s.lab.lemisieur.com`)
    kind: Rule
    priority: 10
    services:
    - name: longhorn-oauth2-proxy
      port: 80