apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  namespace: longhorn
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`longhorn.k8s.lab.lemisieur.com`)
    kind: Rule
    priority: 10
    #middlewares:
    #  - name: oauth2-proxy
    #    namespace: oauth2-proxy
    services:
    - name: longhorn-frontend
      port: 80