apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: lemisieur-k8s-secrets
  target:
    name: oauth2-proxy-secret
    creationPolicy: Owner
    template:
      data:
        client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
        OAUTH2_PROXY_OIDC_ISSUER_URL: "https://login.microsoftonline.com/{{ .tenant_id }}/v2.0"
  data:
    - secretKey: client_id
      remoteRef:
        key: oauth2proxy-azsp-clientid
    - secretKey: client_secret
      remoteRef:
        key: oauth2proxy-azsp-clientsecret
    - secretKey: tenant_id
      remoteRef:
        key: oauth2proxy-azsp-tenantid