apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: lemisieur-k8s-secrets
  target:
    name: github-app
    creationPolicy: Owner
    template:
      data:
        GH_APP_ID: "{{ .app_id }}"
        GH_APP_INSTALLATION_ID: "{{ .app_installation_id }}"
        GH_APP_PRIVATE_KEY: "{{ .app_private_key }}"
  data:
    - secretKey: app_id
      remoteRef:
        key: renovate-ghapp-appid
    - secretKey: app_installation_id
      remoteRef:
        key: renovate-ghapp-appinstallationid
    - secretKey: app_private_key
      remoteRef:
        key: renovate-ghapp-appprivatekey