apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: ""
  settings.yaml: |
    title: homelab
    theme: dark
    useEqualHeights: true
    statusStyle: "dot"
    disableCollapse: true
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 50 # 0-100
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
      provider: google # google, duckduckgo, bing, baidu, brave or custom
    layout:
      home:
        style: row
        columns: 3
      network:
        style: row
        columns: 3

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - home:
      - homeassistant:
          href: https://ha.lab.lemisieur.com
          description: ha.lab.lemisieur.com
          icon: si-homeassistant-#18BCF2
      - homebridge:
          href: https://hb.lab.lemisieur.com
          description: hb.lab.lemisieur.com
          icon: si-homebridge-#491F59
      - scrypted:
          href: https://cams.lab.lemisieur.com
          description: cams.lab.lemisieur.com
          icon: si-homebridge-#491F59
    - network:
      - site-01:
          href: https://site-01.lab.lemisieur.com
          description: site-01.lab.lemisieur.com
          icon: si-ubiquiti-#0559C9
      - site-01-fiber:
          href: https://site-01-fiber.lab.lemisieur.com
          description: site-01-fiber.lab.lemisieur.com
          icon: si-ubiquiti-#0559C9
      - site-02:
          href: https://site-02.lab.lemisieur.com
          description: site-02.lab.lemisieur.com
          icon: si-ubiquiti-#0559C9
      - proxy:
          href: https://srvs.lab.lemisieur.com
          description: srvs.lab.lemisieur.com
          icon: si-envoyproxy-#AC6199
      - nextdns:
          href: https://my.nextdns.io
          description: my.nextdns.io
          icon: si-nextdns-#007BFF
    - hosting:
      - level.io:
          href: https://app.level.io
          description: app.level.io
          icon: si-removedotbg-#2EB4E3
      - proxmox:
          href: https://pve.lab.lemisieur.com
          description: pve.lab.lemisieur.com
          icon: si-proxmox-#E57000
      - docker-02:
          href: https://portainer.lab.lemisieur.com/#!/2/docker/dashboard
          description: docker-02.lab.lemisieur.com
          icon: si-docker-#2496ED
    - data:
      - nas-01:
          href: https://nas.lab.lemisieur.com
          description: nas-01.lab.lemisieur.com
          icon: si-truenas-#0095D5
      - nas-02:
          href: https://nas-02.lab.lemisieur.com
          description: nas-02.lab.lemisieur.com
          icon: si-truenas-#0095D5   
      - pbs:
          href: https://pbs.lab.lemisieur.com
          description: pbs.lab.lemisieur.com
          icon: si-proxmox-#E57000

  widgets.yaml: ""
  docker.yaml: ""