apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: false
    traefik: true
    gateway: false
  settings.yaml: |
    title: homelab
    theme: dark
    useEqualHeights: true
    statusStyle: "dot"
    disableCollapse: true
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 50 # 0-100
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
      provider: google # google, duckduckgo, bing, baidu, brave or custom
    layout:
      home:
        style: row
        columns: 3
      network:
        style: row
        columns: 4
      virtualization:
        style: row
        columns: 4
      kubernetes:
        style: row
        columns: 3
      data:
        style: row
        columns: 2
      monitoring:
        style: row
        columns: 3

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - home:
        - homeassistant:
            href: https://ha.lab.lemisieur.com
            description: ha.lab.lemisieur.com
            icon: si-homeassistant-#18BCF2
        - homebridge:
            href: https://hb.lab.lemisieur.com
            description: hb.lab.lemisieur.com
            icon: si-homebridge-#491F59
        - scrypted:
            href: https://scrypted.lab.lemisieur.com
            description: scrypted.lab.lemisieur.com
            icon: sh-scrypted
    - network:
        - site-01-fiber:
            href: https://site-01-fiber.lab.lemisieur.com
            description: site-01-fiber.lab.lemisieur.com
            icon: si-ubiquiti-#0559C9
        - site-01:
            href: https://site-01.lab.lemisieur.com
            description: site-01.lab.lemisieur.com
            icon: si-ubiquiti-#0559C9
        - site-02:
            href: https://site-02.lab.lemisieur.com
            description: site-02.lab.lemisieur.com
            icon: si-ubiquiti-#0559C9
        - nextdns:
            href: https://my.nextdns.io
            description: my.nextdns.io
            icon: si-nextdns-#007BFF
    - virtualization:
        - proxmox:
            href: https://pve.lab.lemisieur.com
            description: pve.lab.lemisieur.com
            icon: si-proxmox-#E57000
        - portainer:
            href: https://portainer.k8s.lab.lemisieur.com
            description: portainer.k8s.lab.lemisieur.com
            icon: sh-portainer
            namespace: portainer
            app: portainer
        - traefik:
            href: https://traefik.k8s.lab.lemisieur.com
            description: traefik.k8s.lab.lemisieur.com
            icon: si-traefikproxy-#24A1C1
            namespace: traefik
            app: traefik
        - longhorn:
            href: https://longhorn.k8s.lab.lemisieur.com
            description: longhorn.k8s.lab.lemisieur.com
            icon: sh-longhorn
            namespace: longhorn
            app: longhorn
    - kubernetes:
        - argocd:
            href: https://argocd.k8s.lab.lemisieur.com
            description: argocd.k8s.lab.lemisieur.com
            icon: si-argo-#EF7B4D
            namespace: argocd
            app: argocd-server
        - external-secrets:
            description: External Secrets Operator
            icon: si-vault-#000000
            namespace: external-secrets
            app: external-secrets
        - reloader:
            description: Reloader
            icon: si-kubernetes-#326CE5
            namespace: reloader
            app: reloader
        - metallb:
            description: MetalLB Load Balancer
            icon: si-kubernetes-#326CE5
            namespace: metallb-system
            podSelector: app=metallb,component=controller
        - renovate:
            description: Renovate Bot
            icon: si-renovatebot-#1A1F6C
            namespace: renovate
            app: renovate
        - github-arc-controller:
            description: GitHub Actions Runner Controller
            icon: si-githubactions-#2088FF
            namespace: gh-arc-controller
            app: gha-rs-controller
        - github-arc-runners:
            description: GitHub Actions Runners
            icon: si-github-#181717
            namespace: gh-arc-runners
            podSelector: actions.github.com/scale-set-name=gh-arc-runners
        - oauth2-proxy:
            href: https://oauth.k8s.lab.lemisieur.com
            description: oauth.k8s.lab.lemisieur.com
            icon: si-authelia-#113155
            namespace: oauth2-proxy
            app: oauth2-proxy
    - data:
        - nas-01:
            href: https://nas.lab.lemisieur.com
            description: nas-01.lab.lemisieur.com
            icon: si-truenas-#0095D5
        - nas-02:
            href: https://nas-02.lab.lemisieur.com
            description: nas-02.lab.lemisieur.com
            icon: si-truenas-#0095D5
        - pbs:
            href: https://pbs.lab.lemisieur.com
            description: pbs.lab.lemisieur.com
            icon: si-proxmox-#E57000
    - monitoring:
        - uptimekuma:
            href: https://uptimekuma.lab.lemisieur.com
            description: uptimekuma.lab.lemisieur.com
            icon: si-uptimekuma-#5CDD8B
            namespace: uptimekuma
            app: uptime-kuma

  widgets.yaml: |
    - logo:
        icon: https://avatars.githubusercontent.com/u/126491032
    - greeting:
        text_size: xl
        text: HomeLab
  docker.yaml: ""