apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: github
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Resources managed through gitops

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  
  destinations:
  - namespace: 'gh-arc-controller'
    server: https://kubernetes.default.svc
  - namespace: 'gh-arc-runners'
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false