apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: longhorn
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Resources managed through gitops

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  
  destinations:
  - namespace: 'longhorn'
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false