apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: renovate
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Renovate Bot for automated dependency updates

  sourceRepos:
  - '*'
  
  destinations:
  - namespace: 'renovate'
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: ''
    kind: ServiceAccount
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
