apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-app
  namespace: gh-arc-controller
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: lemisieur-k8s-secrets
    kind: ClusterSecretStore
  target:
    name: gh-app
  data:
  - secretKey: github_app_id
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: gharc-ghapp-appid
  - secretKey: github_app_installation_id
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: gharc-ghapp-appinstallationid
  - secretKey: github_app_private_key
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: gharc-ghapp-appprivatekey
