services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.7.0
    container_name: homepage-01
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
      HOMEPAGE_VAR_HOMEASSISTANT_KEY: ${HOMEPAGE_VAR_HOMEASSISTANT_KEY}
      HOMEPAGE_VAR_HOMEBRIDGE_USERNAME: ${HOMEPAGE_VAR_HOMEBRIDGE_USERNAME}
      HOMEPAGE_VAR_HOMEBRIDGE_PASSWORD: ${HOMEPAGE_VAR_HOMEBRIDGE_PASSWORD}
      HOMEPAGE_VAR_JELLYFIN_KEY: ${HOMEPAGE_VAR_JELLYFIN_KEY}
      HOMEPAGE_VAR_JELLYSEERR_KEY: ${HOMEPAGE_VAR_JELLYSEERR_KEY}
      HOMEPAGE_VAR_QBIT_USERNAME: ${HOMEPAGE_VAR_QBIT_USERNAME}
      HOMEPAGE_VAR_QBIT_PASSWORD: ${HOMEPAGE_VAR_QBIT_PASSWORD}
      HOMEPAGE_VAR_PROWLARR_KEY: ${HOMEPAGE_VAR_PROWLARR_KEY}
      HOMEPAGE_VAR_RADARR_KEY: ${HOMEPAGE_VAR_RADARR_KEY}
      HOMEPAGE_VAR_SONARR_KEY: ${HOMEPAGE_VAR_SONARR_KEY}
      HOMEPAGE_VAR_READARR_KEY: ${HOMEPAGE_VAR_READARR_KEY}
      HOMEPAGE_VAR_UNIFI_USERNAME: ${HOMEPAGE_VAR_UNIFI_USERNAME}
      HOMEPAGE_VAR_UNIFI_PASSWORD: ${HOMEPAGE_VAR_UNIFI_PASSWORD}
      HOMEPAGE_VAR_NEXTDNS_ENDPOINT: ${HOMEPAGE_VAR_NEXTDNS_ENDPOINT}
      HOMEPAGE_VAR_NEXTDNS_PROFILE: ${HOMEPAGE_VAR_NEXTDNS_PROFILE}
      HOMEPAGE_VAR_NEXTDNS_KEY: ${HOMEPAGE_VAR_NEXTDNS_KEY}
      HOMEPAGE_VAR_PVE_USERNAME: ${HOMEPAGE_VAR_PVE_USERNAME}
      HOMEPAGE_VAR_PVE_PASSWORD: ${HOMEPAGE_VAR_PVE_PASSWORD}
      HOMEPAGE_VAR_PBS_USERNAME: ${HOMEPAGE_VAR_PBS_USERNAME}
      HOMEPAGE_VAR_PBS_PASSWORD: ${HOMEPAGE_VAR_PBS_PASSWORD}
      HOMEPAGE_VAR_PORTAINER_KEY: ${HOMEPAGE_VAR_PORTAINER_KEY}
      HOMEPAGE_VAR_QNAP_USERNAME: ${HOMEPAGE_VAR_QNAP_USERNAME}
      HOMEPAGE_VAR_QNAP_PASSWORD: ${HOMEPAGE_VAR_QNAP_PASSWORD}
    volumes:
      - /share/containers/homepage/config:/app/config
      - /share/containers/homepage/icons:/app/public/icons
