
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptimekuma
  namespace: uptimekuma
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`uptimekuma.k8s.lab.lemisieur.com`)
    middlewares:
    - name: oauth2-signin
      namespace: oauth2-proxy
    services:
    - name: uptimekuma-uptime-kuma
      port: 3001