apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-auth
  namespace: oauth2-proxy
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Redirect
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-errors
spec:
  errors:
    status:
      - "401-403"
    service:
      namespace: oauth2-proxy
      name: oauth2-proxy
      port: 80
    query: "/oauth2/sign_in?rd={url}"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-signin
spec:
  chain:
    middlewares:
    - name: oauth2-errors
    - name: oauth2-auth