---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-oauth-secret
  namespace: oauth2-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: lemisieur-k8s-secrets
  target:
    name: gh-oauth-secret
    creationPolicy: Owner
    template:
      data:
        client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
        cookie-secret: "{{ .cookie_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: longhorn-oauth-clientid
    - secretKey: client_secret
      remoteRef:
        key: longhorn-oauth-clientsecret
    - secretKey: cookie_secret
      remoteRef:
        key: oauth2proxy-cookie-secret
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`oauth.k8s.lab.lemisieur.com`)
      kind: Rule
      services:
        - name: oauth2-proxy
          port: 4180
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-auth
  namespace: oauth
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth.svc.cluster.local:4180/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - Authorization