apiVersion: v1
kind: Service
metadata:
  name: k8s-api-lb
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
    - port: 6443
      targetPort: 6443
      protocol: TCP
      name: https-api
  externalTrafficPolicy: Local
  selector:
    component: kube-apiserver
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: k8s-api-tcp
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`api.k8s.lab.lemisieur.com`)
      services:
        - name: k8s-api-lb
          port: 6443